version: '3'

services:
 npavlbackendlab1:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./npavlbackendlab1:/npavlbackendlab1"]
   environment:
     PORT: "5000"
     FLASK_DEBUG: "true"
   ports:
     - "5000:5000"
