name: Deploy

on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: windows 10
   steps:
     - uses: actions/checkout@v2
     - uses: akhileshns/heroku-deploy@v3.12.12
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "npavlbackendlab1"
         heroku_email: "n.pavljuchenko@gmail.com"
         usedocker: true